### ISSUE TITLE
USTV

### ISSUE THREAD

**Issue by DeliriouS71** [jwdempsey/USTVnow.bundle#17]
Hi, I noticed since Tuesday (December 30th 2014) that none of the shows on the USTVnow have not been updated. I noticed some new ones were added like The Incredible Hulk, Miami Vice and several others but as far as shows that I have been watching through ustv through plex there hasn't been any updates, are you not doing any updates anymore? My USTV Via Plex has been working so good lately and I truely would hate to lose it after all the bad issues I've had with it in the past. Please if you could let me know I'd really appreciate it!

**Comment by karmadelic702** [comment]
This application is no longer supported due to numerous changes going on at
USTVnow.com.

**Comment by jwdempsey** [comment]
@karmadelic702 is correct. I am no longer supporting this channel. I am not interesting in supporting a site that changes frequently (or even semi-frequently). That being said I would gladly accept Pull requests.

**Comment by DeliriouS71** [comment]
Thank you for all you do and have done but, bummer that USTV has to screw things up all the time! What does "Pull Requests" mean?

**Comment by jwdempsey** [comment]
@DeliriouS71 It means if you want to modify the code then I would be happy to include into the project.

**Comment by DeliriouS71** [comment]
Okay, thanks! I wish I knew how to do that, maybe someone else will be able to figure it out eventually! :)
